language: generic

matrix:
  include:
    # Swift 3.1 macOS
    - os: osx
      osx_image: xcode8.3
      env:
        - BUILD_LABEL: Swift 3.1 on macOS
        - SWIFT_VERSION: system
      script:
        swift test
    # Swift 3.0 macOS
    - os: osx
      osx_image: xcode8.3
      env:
        - BUILD_LABEL: Swift 3.0 on macOS
        - SWIFT_VERSION: 3.0.2
      script:
        swift test
    # Swift 3.2/4.0 macOS
    - os: osx
      osx_image: xcode9
      env:
        - BUILD_LABEL: Swift 3.2/4.0 on macOS
        - SWIFT_VERSION: system
      script:
        swift test
    # Swift 3.0 Linux
    - os: linux
      dist: trusty
      env:
        - BUILD_LABEL: Swift 3.0 on Linux
        - SWIFT_VERSION: 3.0.2
      script:
        swift test
    # Swift 3.1 Linux
    - os: linux
      dist: trusty
      env:
        - BUILD_LABEL: Swift 3.1 on Linux
        - SWIFT_VERSION: 3.1.1
      script:
        swift test
    # Swift 3.2/4.0 Linux
    - os: linux
      dist: trusty
      env:
        - BUILD_LABEL: Swift 3.2/4.0 on Linux
        - SWIFT_VERSION: 4.0-DEVELOPMENT-SNAPSHOT-2017-07-20-a
      script:
        swift test
    # Swift 3.1 iOS 32-bit
    - os: osx
      osx_image: xcode8.3
      env:
        - BUILD_LABEL: Swift 3.1 on 32-bit iOS
        - SWIFT_VERSION: system
      script:
        xcodebuild -project Cheetah.xcodeproj -scheme Cheetah -destination 'platform=iOS Simulator,name=iPhone 5,OS=latest' test
    # Swift 3.2/4.0 iOS 32-bit
    - os: osx
      osx_image: xcode9
      env:
        - BUILD_LABEL: Swift 3.2/4.0 on 32-bit iOS
        - SWIFT_VERSION: system
      script:
        xcodebuild -project Cheetah.xcodeproj -scheme Cheetah -destination 'platform=iOS Simulator,name=iPhone 5,OS=latest' test
    # Swift 3.1 iOS 64-bit
    - os: osx
      osx_image: xcode8.3
      env:
        - BUILD_LABEL: Swift 3.1 on 64-bit iOS
        - SWIFT_VERSION: system
      script:
        xcodebuild -project Cheetah.xcodeproj -scheme Cheetah -destination 'platform=iOS Simulator,name=iPhone 7,OS=latest' test
    # Swift 3.2/4.0 iOS 64-bit
    - os: osx
      osx_image: xcode9
      env:
        - BUILD_LABEL: Swift 3.2/4.0 on 64-bit iOS
        - SWIFT_VERSION: system
      script:
        xcodebuild -project Cheetah.xcodeproj -scheme Cheetah -destination 'platform=iOS Simulator,name=iPhone 7,OS=latest' test

install:
  - git clone --depth 1 https://github.com/kylef/swiftenv.git ~/.swiftenv
  - export SWIFTENV_ROOT="$HOME/.swiftenv"
  - export PATH="$SWIFTENV_ROOT/bin:$SWIFTENV_ROOT/shims:$PATH"
  - swiftenv install "$SWIFT_VERSION"  || true
  - swiftenv global "$SWIFT_VERSION"
  - swift package generate-xcodeproj